### ISSUE TITLE
[Enhancement] Base aurora spawn/despawn on celestial angle rather than wall clock

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#10]
Does the Aurora start and finish based on the Time, or based on the Sky's Light Level. The reason I ask is because we're employing another mod that controls the sunrise and sunset based on the time of year. (The sun comes up earlier in the Summer, and I thought I noticed the Aurora persisting through dawn.)

Sorry for slamming you with these issues/questions/requests.

**Comment by OreCruncher** [comment]
The questions are fine.  I find out about mods I haven't heard before. :)  Auroras spawn at night time hours, where night time is defined as having Minecraft time >= 13000 and <= 23500.  If a player is logged in at dusk they could see an aurora fade in, and at dawn they will see it fade out.  If it is night time and they move into a biome that triggers auroras one will spawn and fade in.

Things should work OK if the time altering mod actually alters the Minecraft wall clock.  For example, I have tested the mod with TimeScaler and it works as intended because TimeScaler takes control of world time accounting.  Which mod are you using to manipulate time?

**Comment by PitchBright** [comment]
That's awesome, I'm glad you're open to ideas/requests/questions like this. Your work here is pretty awesome, and it touches on a few things I've been dabbling with myself. I've got a small laundry list of things I'm looking to code and implement, perhaps we'd all be in better hands if I gave you the list and let you pack a few of them in BetterRain, lol. :D 

I'm working with Stellar Sky. https://github.com/Abastro/StellarSky
It does affect the wall clock, but I believe it does so based on the Sun's position, judging by how it swings pretty quickly from the 10am position to the 2pm position (on the clock), as the low Sun in the Winter crosses the longitudinal plane.

**Comment by PitchBright** [comment]
I re-read your response… and just to clarify, StellarSky doesn't touch "time". Just the Sun's position in the sky at various times.

**Comment by OreCruncher** [comment]
If all it's doing is handling the "stellar" rendering and not touching the time then I guess you can get things like this.  My algorithm uses fixed start/end because it assumes that the length of night and day are fixed length which is typical of Minecraft.  Not entirely sure I can address this - need to look into Stellar Sky and see what hooks it provides.

**Comment by PitchBright** [comment]
Yeah, you're right.. it's a pretty atypical. Most of your users wouldn't care two-shakes about being able to config the times, but I know for sure that Stellar Sky users WILL want to… because they've been begging Abastro to add Auroras in his mod.. they'll be crazy for your mod as soon as they find out about it.… so I might be a little bit out-in-front of things on this little quirk between the two mods. Maybe something based on LightLevel, or Configgable start/stop times (maybe a combination of both)… if there isn't an adequate hook there?

Actually, I can just ask Abastro to put a hook in if you need one. Just et me know what you want, or request it on the git… and I'll let him know it's coming from an issue I raised with you here. He'll probably getcha whatcha need pretty quick.

**Comment by OreCruncher** [comment]
I took a look at it and I may base aurora spawn on the current celestial angle.  If I did this it would work with Stellar Sky and I think it would work with other time scaling mods like TimeScaler.  I need to experiment.

**Comment by PitchBright** [comment]
Aight, cool. Lemme know if you need anything from the StellarSky side of things, and feel free to let me know if you want me to test stuff before you release anything. I'm usually sitting here, at the ready, and a lot of guys send me their previews so I can confirm/deny bugs they've fixed before they release it out.  I'm more than happy to help however I can.

**Comment by OreCruncher** [comment]
Thanks!

**Comment by OreCruncher** [comment]
Pushed a build to CurseForge that spawns auroras based on the celestial angle. http://minecraft.curseforge.com/projects/better-rain/files

**Comment by PitchBright** [comment]
Okay, I'll test that out and see how she plays. Thanks.
