### ISSUE TITLE
[Feature Request] Customizable Elevation Haze

### ISSUE THREAD

**Issue by Jomik** [OreCruncher/BetterRain#102]
Tried with both DynamicSurroundings-1.8.9-2.0.4.10 and DynamicSurroundings-1.8.9-2.0.5.2BETA.

Elevation haze works perfectly up to around 120-130. When you go above this height, it fades out. So at extreme heights  you have no elevation haze and perfect visibility.

I don't believe this is intended.

**Comment by OreCruncher** [comment]
Yes, that's the way it currently works.  Reason is that folks were building above cloud height and they couldn't see.  I made  a change so that it works in a band at cloud height.

**Comment by Jomik** [comment]
I see, then would it be possible to add an option to modify the "height" of the band? So that I could have it work from cloud height to the ceiling of the world? I'd prefer it even though I build up there.

Feature request, I guess.

**Comment by OreCruncher** [comment]
The elevation haze is on my list of things to go back and look at.

**Comment by OreCruncher** [comment]
Added a configuration option to turn off the band haze effect.  When this happens the behavior will be like a gradient where it starts getting foggy at cloud level and gets more dense the higher the player goes.  Note that the effect will be different than before if a player is "inside".  When "inside" (there are cover blocks in an area around the player and above the head) the fog distance will be pushed out so that the fog is not inside a medium sized structure.

**Comment by OreCruncher** [comment]
BETA with feature change posted to CurseForge.
