### ISSUE TITLE
1.8.9-Compatibility w/ Weather 2 Mod

### ISSUE THREAD

**Issue by WenXin20** [OreCruncher/BetterRain#110]
There are no sandstorms in the desert when the Weather mod is combined with it.

**Comment by OreCruncher** [comment]
Did you set `Particle_RainSnow` to `false` in the Weather2 config?

**Comment by WenXin20** [comment]
No

**Comment by OreCruncher** [comment]
Set it to false and see if it starts working.

**Comment by WenXin20** [comment]
That works

**Comment by OreCruncher** [comment]
Cool.  Unfortunately there isn't a way to have that setting `true` and get Dynamic Surroundings weather effects.  The reason is that both Weather2 and Dynamic Surroundings want to control rain rendering.  By setting `Particle_RainSnow` to false tells Weather2 not to do the rain rendering which eliminates the conflict.

Closing out the report due to workaround.
