### ISSUE TITLE
Lightning

### ISSUE THREAD

**Issue by Fortist** [OreCruncher/BetterRain#117]
Ive been playing for a while, and Ive never really noticed lightning, if at all.
They still exist with this installed, right?
Also, a suggestion; Lightning Storms varying from no rain to heavy rain.

**Comment by OreCruncher** [comment]
Yes, lightening can still happen.  I did think about lightening storms but I am not sure exactly what I want to do with it.

**Comment by O13SC3N3** [comment]
All you gotta do OreCruncher is use my world on the server lol... Rains all the time, and rains lightning down around everyone... good times.

**Comment by Fortist** [comment]
Yeah, after playing with this for the longest time, I dont think Ive ever seen natural Lightning, once. 
When even forcing a lightning rain, not a single bolt.

**Comment by OreCruncher** [comment]
To have lightening occur there are several things that need to happen:

1.  It has to be raining.  There is a timer for this.
2.  It has to be thundering.  There is a timer for this, too.
3.  Rain strength has to be > 90.

So the rain and thunder intervals must overlap, and the rain strength has to be > 90.  Storms at the upper end of the scale are more rare because the strength of a storm is based on a bell distribution, with 0 and 100 at either end.

With the current releases (and the unofficial port) you can influence this by setting the minimum rain strength in the dimension to 91.  This will result in storms being on the strong end, but it will cause lightening when the thunder is active.  I should also point out that this puts the rain at more the vanilla intensity (which is always 100).
