### ISSUE TITLE
[Enhancement] Config option for changing duration/interval of rain

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#119]
Current logic uses the Minecraft logic for determining the duration of rain as well as the interval between storm events.  Would be nice to have config options that allow a player/server owner to configure these options.

**Comment by PitchBright** [comment]
My buddy found his code from 1.4.7.

My config file had this:

```
rain {
    I:RainDownConst=864000
    I:RainDownRand=2592000
    I:RainUpConst=1000
    I:RainUpRand=71000
    I:StormDownConst=144000
    I:StormDownRand=1
    I:StormUpConst=1000
    I:StormUpRand=23000
}
```

Rain = deals with rains
Storm = deals with storms
Up = active
Down = inactive
Const = minimum time it rains for
Rand = maximum additional random time
--time that rain/storm is active or not is (Const + some random between 0 and Rand)

He commented:

The method was changing "updateWeatherBody" in World so the hardcoded numbers were configurable instead of hardcoded, as well as do some stuff in "wakeAllPlayers"/"areAllPlayersAsleep" in World for altering how sleeping changes weather (and how it resets the counter).

**Comment by OreCruncher** [comment]
Making a copy to the new repository so I don't lose track of it.

**Comment by PitchBright** [comment]
Okay, cool.

Also, it's low-priority/not-necessary for me now, so don't go out of your way or anything on my behalf. We ended up just making our own mod that does it itself.

I believe Abastro forked this mod and took over maintaining it because he thought you had abandoned it.

You may want to check in with him to see if what he's done since, would be useful to you.

https://github.com/Abastro/BetterRain/commits/master

**Comment by OreCruncher** [comment]
Already been in communication with him about it and I am working on my 1.10.2 version.  I need to do some refactoring and what not.  The changes above are pretty straight forward and in the area I am currently working on.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
