### ISSUE TITLE
[Enhancement] More selfish sounds and pretty things with water

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#21]
So, I read in the changelog for 1.0.2.3 Beta, that, for selfish reasons, you added "ambient" sounds to lily pads and ice blocks (also, does this include packed ice?). After reading that, I think you (and by you I mean me asking you nicely) should "selfishly" add bird sounds or wind sounds to leaves (maybe have it through Tags, like -leafblockAll or whatever it is so mod leaves work). It would be really cool, and would make this mod so much better.

I don't know how far your willing to take aesthetic pretty things with this mod, I know you want it to be so that it doesn't directly effect items/blocks/mobs so servers arn't required to have it, and it can be a client side mod, But maybe having something like waves in the distance in ocean biomes? I currently have a seed that I love (and have so many mods that I can't tell you which ones you'll need to re-create it without giving you all 150 of them XD) that has oceans all around it (I really havn't explored much, just along the coasts really), and I think it would be so cool to see waves in the distance or even just some water lapping at the edges.
I don't know if this is even possible at the moment with the current GL limitations and the time that you have to invest in such a feature...

While I'm here, I might as well ask (I think I already have but I can't remember) if you can/plan to do any minor aesthetic changes to minecrafts clouds? Someone already said that BR is slightly incompatible (by slightly I mean the main feature of the mod Q AQ) with Crono's Weather Mod. I kinda like the volumetric clouds, or atleast something that isn't a texture-map at a set hight moving in a northernly (I think its north still, It might be wet now) direction.

**Comment by OreCruncher** [comment]
See [#20].  This is something I am actively working on.  The way I have it working currently is that each biome type can have a sound configured.  Using your example above a pack author could configure a wave crash sound for beach biomes, and general water wave sound to ocean biomes.  This is over and beyond the block specific sounds.

The sounds I have going in as part of BetterRain are are Wind (configured for "hills" biomes), Forest (configured for "forest" biomes), and Crickets (configured for plains and meadow biomes at night).  It would be easy to add wave sounds assuming the sound clip is long enough because the sound will loop.

EDIT:  Have a decent wave sound for beach/ocean.  Lowering the pitch a bit I can get deep ocean, too. :)

Oh, didn't answer the question RE: Weather 2.  If you tell Weather 2 to let Vanilla handle rendering the rain ("Particles_RainSnow" set to false in the advanced config) BetterRain will handle the rendering and display auroras.  Weather 2, though, will manage the rain intensity through it's weather mechanics.

**Comment by Drakoflame** [comment]
I was talking about litteral (aesthetic) waves. Something that you could physically see rising out of the water, like an aurora, on its side, in the water XD

**Comment by OreCruncher** [comment]
That is an entirely different animal. I wouldn't know how to even start doing something like that..  Would be cool, though.

**Comment by Drakoflame** [comment]
I was just thinking it would be something far off, something that you couldn't really interact with because its just a pretty thing that's there. I don't even know if its possible, and the rest of my idea was just because of what you said about lily pad frogs and things like that. Hell, I even went and downloaded the most latest (yet very outdated p nq) mAtmos and Presence Footsteps because of what you said

**Comment by OreCruncher** [comment]
Latest BETA versions have background sounds configured for Forest, Beach, Ocean and Deep Ocean: http://minecraft.curseforge.com/projects/better-rain/files.  I am going to open another entry for ocean waves visuals.

**Comment by PitchBright** [comment]
Just chiming in here because you're really exploring areas outside of rain, with a lot of what you're doing and also planning to do… I think renaming the mod would be a good idea, and the sooner the better, because the longer it remains "Better Rain" the more brand equity that builds, and the longer people who aren't interested in a rain mod, will likely pass on investigating this mod… consequently missing out on all the other awesome stuff. I've been thinking about this since right around the time I started using it :)

Spitballs for the brainstorm box:
BetterEnviroment
BetterAtmosphericEffects

(if you're intent on keeping the 'Better' handle)

**Comment by PitchBright** [comment]
Also +1 for the better clouds, that was on my list o' things to talk with you about. :P

**Comment by OreCruncher** [comment]
lol - yeah, I have to do something about the name.  Not sure exactly what I want.  My thought was to call it BetterRain Plus.  I am not endeared to "BetterRain" but at the moment maintaining a tie may be worthwhile because of documentation, links, etc.  I have to talk with the CurseForge folks to see what the effect would be if I renamed the project - I don't want to mess up any web links because of automated modpack tools.

**Comment by OreCruncher** [comment]
Closing out since the topics touched on in this entry are covered in other enhancement incidents.  If anything is missing please open a new incident for each topic.
