### ISSUE TITLE
[Enhancement] Weather in the Nether

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#27]
Nether weather. _(I'm funny!)_

The "precipitation" visual would feature hazy, brownish-gray specks, and would move like snow, giving the impression of ash settling out of the air. It would be accompanied by cinders (the same particles that bubble out of lava) that fade in and out of view and drift around slowly. Reddish fog would close in and reduce visibility. The sandstorm-blowing-wind sound could be recycled, possibly accompanied by a distant rumbling noise. Fire jets have an increased spawn rate. The overall atmosphere is that of a volcanic eruption.

... okay, so calling this "weather" is stretching it _just a little_. But the nether's current atmosphere is too... quiet and nonthreatening? Having it periodically "erupt" would certainly make journeying through a molten hellscape of tortured souls feel more exciting. It could also work in overworld volcano biomes.

**Comment by OreCruncher** [comment]
I have been thinking about the Nether and what types of effects it could have.  I am not sure it has a rain/snow cycle - would have to look at the MC code to see how it plugs in.  Essentially it would have similar effects to the desert with periodic "fireballs" raining down.  The other thing I would have to look at are the biomes added by other mods - there may be some other interesting effects I could add there as well.

**Comment by OreCruncher** [comment]
Partial progress toward this goal.  Have fog in the Nether during rain.

**Comment by apotheoseGrifter** [comment]
There could be some really interesting integration with Biomes O' Plenty on this. Visceral Heap is just begging for periodic rains of blood, just as one example. It's rather a lot of work for visual effects that would only work with one mod, though, so maybe not. Perhaps instead there could be generic effects that hook into biome types? A few examples I can think of are fireflies occasionally floating around in forested areas at night, st. elmo's fire during thunderstorms at sea and in magical biomes, will o' the wisps in magical biomes... That moves out of the scope of this particular suggestion, though, and perhaps out of the scope of this mod.

If you're interested in this type of thing, though, I could create a separate issue and brainstorm some more ideas. :D

**Comment by OreCruncher** [comment]
One of the things I am doing is refactoring the implementation to better support biome specific precipitation effects so I can better support modded biomes.  This system would be used to quickly add support for biomes as a default as well as providing methods for pack authors to customize.  In the example you give for the Visceral Heap a pack author could provide a custom rain texture for the biome via a resource pack and configure Dynamic Surroundings to know about and use that texture.

(Not sure if anyone has really clued into this just yet but it is possible to create a resource pack containing custom sounds that can be hooked into Dynamic Surroundings using the Biome Configuration system.  I plan to extend this to textures as well at some point to support rain textures.)

As for things like fireflies, will-o-wisps, and ball lightening I think these would have to be mobs rather than particle effects.  It's why I haven't committed to doing those things.  Right now I am trying to limit things to client side particle effects and what not.  I haven't totally dismissed the idea, I'm just not all in at the moment.

**Comment by apotheoseGrifter** [comment]
That's great! Sounds like it would be fairly easy to add support once that's finished, which will make some modded biomes much more atmospheric.

As for the second part: Well, I used to think it was kind of strange that Better Foliage added those reeds and coral reefs that you couldn't interact with, but after a while they seemed to be perfect additions to the game. While there is some odd behavior with them, they make the world feel a lot more alive without cluttering up your inventory with useless junk when you start breaking things.

With that in mind, it's really just one more step further to add fireflies and such as particle effects rather than mobs-- no model required, the texture could be very tiny and simple, you wouldn't have to figure out the AI (could use bats, but they're a bit too fast and chaotic), they're less intensive in large numbers (as far as I'm aware, anyway), players won't accidentally attack a firefly while fighting enemies, and so on, all while still preserving the atmospheric benefits. Certainly, Twilight Forest's firefly mobs could've been particle effects and they wouldn't have lost anything for it.

**Comment by OreCruncher** [comment]
My thought for making a mob rather than particle is longevity as well as feel across players on a server.  Particle entities exist purely client side and don't persist.  The player experience on multi-player servers would be strange in that "hey, you see that wisp?" and the other player says "what wisp?". :)  Though I haven't looked thoroughly at it I suspect that I can tweak the mob entity so that there isn't a hitbox, etc. so they wouldn't screw up combat, can't be killed, etc.

(Note that fireflies have a better chance at being a particle effect and it may be the route I go for them.)

**Comment by apotheoseGrifter** [comment]
Hm, that's true, although that's also a potential problem for Better Foliage and it doesn't seem to be particularly hindered by it. I've seen plenty of mods that could optionally be used on the server to sync clients (though not specifically for this type of thing, I think), so it seems reasonably possible to eliminate it as long as everyone has the mod.

This is not to say I really have anything against a mob-based implementation; it's just that mobs solely meant for cosmetic atmospheric purposes will cause just as much lag as mobs that are actually useful and may crowd out the latter in some cases.

**Comment by OreCruncher** [comment]
This mod would have to be on the server.  Aurora spawning/tracking is handled server side.  I could spawn the wisp type particle on the server and send a packet to each client.  But then, the wisp instance on each of the clients could drift different directions since they are long lived.  If need to sync all this stuff across clients it would be better to make it a mob and let the existing Minecraft/Forge framework do the heavy lifting.

In terms of lag I don't think it would be too much server overhead.  The mob wouldn't have a complex AI since it wouldn't care about targeting, escape, etc.  It would just drift place to place.  In respect to a client it would be a wash because whether it is a particle or mob the client would have to render and deal with it.

If they were mobs they would be in the same category as bats.  Wouldn't interfere with hostiles or animal mob spawning since caps are applied per category of mob, not grand total.  I don't anticipate spawning large quantities of these guys - they would be a smaller amount.  If it did become an issue there tweaks that can be made to adjust the caps.  (My other mod Restructured has options to do just that.)

The other thing to consider particle vs. entity is that particles have a much closer render range boundary than mobs.  The Minecraft particle handling system culls particles that are > 16 blocks distant from the player.  There are exceptions and some holes in their approach but this is the general limit.  I could play some client games to make it work at longer ranges but there may be a limit.  Mob entities have a default render range of 64 blocks so they can be seen quite a distance.

Regardless, I have made no decisions related to the direction.  I am still weight pros/cons of the approach.  My goal is to have an effect that has simple mechanics internally and not create maintenance problems for myself in the future.

**Comment by OreCruncher** [comment]
Code changes to support red dust and smoke "splash" particles in the Nether.  There is no such thing as outside so these effects occur everywhere, even in tunnels.

**Comment by OreCruncher** [comment]
Completed Nether iteration for this go around.  Next step would be a major overhaul of weather rendering to permit better customization.  BETAs posted to CurseForge.
