### ISSUE TITLE
[Enhancement] "What was that...."

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#43]
Deep, deep under the water, near the ocean floor, where light doesn't reach, and will never reach by natural means. A lone person builds, using mechanical means to breath, and highly advanced ways of repelling the water, several electric lights light up the under water base but that still doesn't drown out the sounds... the groans, the alien cries of... _SOMETHING_ that's down there with them...

Basically, whale sounds or other sounds (that can easily be found by going to youtube and searching "alien water sounds" XD) that play when below Y = 60 and Biomes is ForgeDictionary <Ocean> = True (I dunno... I throwing random things here XD) there could be a small chance (1 in 2000 ticks or so) that one of the sounds play while deep under water.

This is inspired by my personal fear of deep water. I hate not knowing whats under/around me, so hearing some sort of unearthly cry while deep in the dark... well lets just say it adds to the creepy and ambiance~

**Comment by OreCruncher** [comment]
lol - I had similar thoughts and that is why I created [#41].

**Comment by Sunconure11** [comment]
https://en.wikipedia.org/wiki/Bloop

This is a good example of a sound that could be added via such an option.

Here's a bigger list:

https://en.wikipedia.org/wiki/List_of_unexplained_sounds

And if you want something even more eerie, look up number stations. They are not deep ocean, but, they could work for ruins for a random "WTF!?" moment.

**Comment by Drakoflame** [comment]
@Sunconure11 I think that the Number Stations could work for something if Cruncher adds support for Wasteland biomes. Say, whenever your near a generated structure (how you would tie into those I don't know... maybe test for noteblocks/jukeboxes in the wasteland biome?) and have them randomly play a string of those numbers? That would actually be really really cool, and very _VERY_ creepy :D

**Comment by Sunconure11** [comment]
@Drakoflame: Just remember, some number stations are not just strings of numbers played over and over again. Here are some examples of what I mean (you might want to turn down your volume):

https://www.youtube.com/watch?v=n7cAyZ8jXfs

https://www.youtube.com/watch?v=y8LQMDQAoVk

Also, this should only be applicable to generated jukeboxes and noteblocks, not player-placed ones, if that is possible.

And here is an entire site dedicated to number stations sound clips:

https://archive.org/details/ird059

**Comment by OreCruncher** [comment]
For the water environment those are the types of sounds I am looking for.  Downside is that the free (public domain) are low quality or have a bunch of other noise.  It seems to me that these sounds could be generated using tools, but I don't know how to do that. :\

As for Number Station stuff I have a system in place where a sound can be played at a block.  It's how I supply sounds for lilypads, ice cracks, etc.  With this system I can tie any sound to a block so that it randomly plays when a player is nearby.  Currently the block sound system is not available for configuration by Json files.  There is more work I have to do in this area to make it possible.  My goal is to do something like spot sounds for biomes, but associate them with a block rather than a locale.

(When I read the description above I had an image of those structures generated by RFTools.)

**Comment by OreCruncher** [comment]
Found some whale sounds - will be in the next BETA.  Also found some decent underwater background sounds for ocean/deep ocean - river is a bit of a problem.

Also, spot sounds for blocks will be in the next BETA as well.  A modpack author will be able to associate a sound with a block similar to what Dynamic Surroundings does with waterlilies and frog croaks.

EDIT: If you have a decent set of sounds for a jukebox in a wasteland biome let me know.  I could add that as a default.

**Comment by Sunconure11** [comment]
Just look through these, there are links to download them:

https://archive.org/details/ird059

Downside is that they aren't the highest quality. This could work for old jukeboxes though simply because of that though.

**Comment by OreCruncher** [comment]
Opened [#56] to track.  Closing.
