### ISSUE TITLE
Water drop sounds overwelming.

### ISSUE THREAD

**Issue by mindcloud69** [OreCruncher/BetterRain#45]
The water drop sounds are overwhelming especially when it is raining. It over powers everything else and doesn't actually sound like a water drop at all(the echo maybe?). I would suggest a much softer sound a very soft pat sound played far less often. There are some good examples [on this video on youtube](https://youtu.be/lWOG20x4Dds?t=18m54s). For now I have replaced the water drop sounds in the jar with silence. Other than that GREAT mod and I hope you continue it. I always loved presence footsteps and MATMOS but they were always buggy.

**Comment by OreCruncher** [comment]
The next BETA is going to have tweaks for that.  I turned down the volume as well as tweak the conditions under which it played.  You know those obsidian sheets that form over lava pools when you dump a bucket of water?  Minecraft generates water drop particles on the underside of those sheets just to have them fall into the lava block right underneath. Had to put in code to detect that and not play the sound otherwise it would sound - stupid.

**Comment by OreCruncher** [comment]
Posted an update to CurseForge that has reduced volume for water drops: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
