### ISSUE TITLE
Possible incompatibility between latest builds of this mod and latest builds of stellar sky

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#46]
The incompatibility is that the moon appears to be invisible when both mods are installed, and the issue only goes away if one or the other are removed.

Did you do anything recently that could be affecting this?

**Comment by OreCruncher** [comment]
Try setting "Fancy Cloud Handling" to false in the dsurround.cfg and let me know if it begins to work.

**Comment by Sunconure11** [comment]
That didn't do anything it seems.

**Comment by Sunconure11** [comment]
Probably a user error on my part. Check this issue: https://github.com/Abastro/StellarSky/issues/26

**Comment by OreCruncher** [comment]
I wish there was a command to make the moon come out....

Best I can tell it is working. I double checked the code (without the fancy cloud render hook) and things didn't change that would break it.

Where fancy cloud treatment is concerned both StellarSky and Dynamic Surroundings want to "wrap" the world provider so it can tap into Minecraft operation - StellarSky wants to hook sky rendering, celestial angle calcs, and moon phase stuff.  Dynamic Surroundings wants to hook cloud coloration and cloud height queries.  They don't step on each other.

I do have a concern because StellarSky does not forward all calls to the "real" provider.  To mitigate that causing a potential issue I lowered my mods event handler priority so that I get the last shot during world load.  This creates a chain so that Dynamic Surroundings forwards calls to StellarSky, and it in turn can forward calls to the "real" provider as needed.

(This explanation is intended for those that may know how world/world providers relate so they can get a better idea of how we hook the providers for a world/dimension.  I am not sure there is a potential bug here, but I thought being more defensive is a better way to go.)

**Comment by OreCruncher** [comment]
@Sunconure11 Have you been able to determine if it was indeed user error?

**Comment by Sunconure11** [comment]
Pretty certain.
