### ISSUE TITLE
Sky effects/weather

### ISSUE THREAD

**Issue by endguy14** [OreCruncher/BetterRain#48]
Moon eclipses (solar,Lunar) Comets,Meteor showers,Shooting stars.Weather effects like evaporation,wind,Severe weather,Hail,etc

**Comment by OreCruncher** [comment]
Some of these seem to belong in the StellarSky mod (comets, meteors, etc.).  As for the severe weather (hail and what not) check out Weather 2.  It even has tornadoes. :)

In terms of evaporation this would be an interesting effect.  However, I think it is beyond the scope of what I am trying to do with Dynamic Surroundings.  The mod is just visual and sound effects.  Something like evaporation touches on game mechanics, or at least my idea of evaporation (water block losing volume over time, and gaining volume due to rain).

Good ideas, though.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
