### ISSUE TITLE
Looking for feedback on default sound volumes

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#51]
I need opinions on the current sound volumes and suggestions as to what they should be.  I have a [page](https://github.com/OreCruncher/BetterRain/wiki/Sounds-in-the-Mod) on the wiki that provides information on the sounds Dynamic Surroundings has as well as how to play a sound at various volumes using `/playsound`.  If you want to help, do the `/playsound` thing and report your opinions in this issue.
- [x] BoP Kelp Forest Funnies
- [x] New rain drip
- [x] New Jungle sound
- [x] Longer fad out
- [x] Adjust sound volume
- [x] Look at Ambiotic
- [x] Play spot sounds randomly away from the player

**Comment by Ariannae** [comment]
Currently I'm enjoying the ambience that you've provided, with only a couple of issues.
My first issue are the water droplets. I almost think that there should be a limit to how often or how many blocks can trigger this sound. If you build a house underwater, for example, the sound gets old pretty quick. I'm not quite sure how to alleviate this though. Like I said previously, putting some kind of limit could potentially help (Ie, a maximum of 3 blocks can trigger this noise at any time?), maybe lowering the volume again, or possibly just changing the actual sound to something softer/less harsh? The best way I can describe this is to change it to a "plip" noise, instead of sounding like the drop is falling onto something plastic.

The sounds can also get somewhat repetitive. For example, I think cutting the background sound in Jungles to only the cicadas/buzzing noise and adding the monkey, frog, and other animal noises as separate noises that play at random intervals along with the background track would cause the environment to feel like it was dynamic, and there would be far less repetition.

A longer fade-out might be a good thing as well, or have the biome's background noise gradually decrease in volume the further away from that biome you get. This way, moving from a Jungle into a Forest wouldn't immediately put a stop to the Jungle's noise, but would gradually get softer until you were a bit away from the jungle and all of its wildlife.

One other issue that is more of a conflict; certain biomes trigger ambient noises when they shouldn't due to how they're registered (Biome O' Plenty's Kelp Forest triggers the Forest noises, which is pretty hilarious). I believe you've added options to fix this on the user's end, but I haven't gotten a chance to check those out yet.

Other than those minor things, I'm really enjoying what you've done. I would suggest possibly looking into [Ambiotic](https://github.com/Ambiotic/Ambiotic) ([Minecraft Forum page](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2530955-ambiotic-v1-2-0-matmos-inspired-ambient-sound)) if you plan on delving deeper into the atmospheric noises. I really like what that mod author's done (I personally find it to be better than even MAtmos), but it looks like they are on hiatus due to work. It'd be amazing to see some kind of merge between Ambiotic's sound system and your environmental effects.

Edit: I'm dumb. You wanted feedback on the actual volume of the noises. In regards to that, my previous opinion on the water drops still stands, but I also feel like rockfall sounds off. It sounds like it is occurring right next to the player when there are no rocks actually falling within sight. I think it should be a muffled noise, as if rocks are falling in the distance, or in a cavern nearby. I think the owl noise is a tad too loud. It should be a little bit fainter, as though the owl is perched in a tree and not right on top of the player. I really like the Soulsand sound though (And it pairs -very- nicely with Better Foliage's little souls rising from the block).

**Comment by OreCruncher** [comment]
Thanks for the feedback.

The water droplet is one that I am constantly looking at and tweaking.  I have made additional code changes to cull drop sounds as well as changing the sound itself.  Also, in the next BETA sound volumes will be further reduced so the drop will not be as loud.

The jungle sound needs work.  As you point out that are some rather distinct sounds in that track that makes it easy to identify as repetitive.  I need to find a jungle sound track that avoids distinct sounds.  And since I now have spot sound capability I can add jaguars, monkeys, etc. as spot sounds to get some additional feel.

I plan on looking at a longer fadeout during the biome transition.  For me its a matter of tweaking an internal data value to make it last longer.  While typing this is occurred to me that I can have different times for fade in than out.  I will have to explore that.

Yes, the Kelp Forest was pretty funny.  I was testing yesterday and came across that and started laughing.  The next BETA will have config changes to better support BoP.

Ambiotic - I will look at that.  Right now most of the sounds the mod uses are samples from recordings.  The cool thing about that is you get realistic sounds.  Downside is that the ogg (sound) files are pretty large and causing the JAR to bloat in size.

**Comment by Ariannae** [comment]
Ambiotic also has some phenomenal background noises. I'm not sure if you'll be able to find exactly where the author obtained them from (Nor do I know if it was a free source), but I'd absolutely recommend looking into those.
I also wouldn't consider the JAR to be bloated in size, even if the size was doubled. It's not like you're randomly throwing noises in there; they're definitely helping with immersion. People tend to underestimate how much more immersive noise can make something. More often than not, I'd be willing to take higher quality sound over better graphics (Morrowind, anyone?).

**Comment by OreCruncher** [comment]
Found some good replacements for the water drop.  Sounds more like water hitting concrete - the "plip" noise you are referring to.  No reverb. 

EDIT: Started taking a look Ambiotic.  Trying to "solve" some of the sound issues but in a different way.  I haven't listened to his sounds yet.  And I agree - not sure of the pedigree of the sound files.  May find out more when I look at the metadata.

**Comment by OreCruncher** [comment]
It was mentioned that the "falling rock" sounds didn't feel off in the distance.  The reason is because the sound is positioned "right between Steve's ears".  I will experiment a little bit with moving the point to some random location around the player to see if I can improve the effects.

**Comment by OreCruncher** [comment]
Started [#56] for sound suggestions

**Comment by OreCruncher** [comment]
Looked at Ambiotic.  In general trying to do similar things but in a different way.  With Ambiotic a set of conditions are defined for a sound using JavaScript expressions.  This expression is evaluated to determine if a sound will play.  With Dynamic Surroundings sounds are attached to a biome, real or otherwise, and regex is used to do the filtering based on a condition string that is generated by the mod.  Not saying one way is better than the other, just pointing out it is different.

Some of the sounds supplied by Ambiotic are nice as well.  Not sure of the pedigree, or what license is set for Ambiotic.  By default assume no license.  Have to check with the author.

**Comment by Lonemind** [comment]
Did you recently add a hunger sound to your mod? If so I have noticed that it will begin at a little less than half full hunger then continue growing more intense even after you eat. It becomes quite deafening after a few minutes. I have to relog on the server I play in order for it to cease.

**Comment by OreCruncher** [comment]
Yes, it was recently added bacl in *.0.4.3.  Triggers when hungerbar is <= 40%.  It shouldn't fade in - it happens and there is a delay between plays.  Shouldn't get louder, and after getting your hunger > 40% it should stop.  Which mod version do you have?

**Comment by Lonemind** [comment]
I am using the private version you made for the players that were crashing upon joining a server today in this issue. https://github.com/OreCruncher/BetterRain/issues/59

**Comment by OreCruncher** [comment]
OK - moving to the latest released BETA version may help.  I pulled out a work around for sounds "disappearing" because it introduced additional side effects.  What you may be experiencing is that the tummy grumble sound being sent down into the sound engine repeatedly because the Minecraft sound manager that sits on top is no longer tracking the sound for some reason.  Because they stack on each other it seems to get louder, etc.

(I have this circumstance duplicated in my development sandbox and trying to figure out a way to resolve.)

**Comment by Lonemind** [comment]
Excellent. Thank you for the help, Ore.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
