### ISSUE TITLE
[Enhancement] Particle "mobs"

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#58]
Consolidating suggestions for particle "mobs".  These things are purely client side particle effects and the player cannot interact with them.  However, they do have an AI of sorts where they can move based on rules and disappear when conditions require.
- [ ] Will-o-wisp
- [ ] Ball lightening
- [ ] Fireflies
- [ ] Dust Devil/Water Spout/Fire Cyclone
- [ ] Flying Saucer (OK, maybe not - Kids in the Hall anyone?)

**Comment by O13SC3N3** [comment]
I like it, maybe attach a Will-o-Wisp to a tree? spin around a few times and vanish? (Very low chance) since there is so many trees in forest biomes lol. Fireflies be cool in swamps, and even some forest types. Dust devil be cool. Flying Saucer? Shooting Star maybe. But it all have to be minimal at best.

Be interesting on how you would implement this tho.

**Comment by Sunconure11** [comment]
For magical biomes (not biomedictionary spooky ones though), what about fairies or pixies? They should have an option to be disabled though.

**Comment by OreCruncher** [comment]
Possible.  Other thing I thought of was a ghost.  Essentially render a spectral form of a random mob as a particle.  Sounds great in theory but I have no clue as to how to accomplish that as of yet. :)

**Comment by O13SC3N3** [comment]
Im sure it could be achieved with rendering on a block condition of sorts, with a rare chance. or even with specific mod intergration. When it comes to pixies lets not forget BoP beautiful secret world that was removed due to the issues with the Pixie ;p but that was entity related and wouldnt obey spawning rules. And Forge rules for neutrals sucks anyways.

**Comment by Sunconure11** [comment]
We could have ghosts in biomedictionary spooky biomes.

For end biomes, what about some kind of small eldritch abomination? Just to give the illusion that forces greater than you are watching you...

For the nether, maybe ghastly faces that appear very rarely?

**Comment by O13SC3N3** [comment]
Better Foliage adds little moaning ghost faces from the soul sand, with Dynamic Surrounding's laughing it works great. You might be able to attach to better foliage to set off a lot of conditional sounds. Which is purely client side. IE the Reeds, Algae, etc.

**Comment by AlienXtream** [comment]
YES PLEASE! :)

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
