### ISSUE TITLE
Potion Display Issue

### ISSUE THREAD

**Issue by O13SC3N3** [OreCruncher/BetterRain#64]
Seems to be an issue with the potion hud when its altered in anyway, size, opacity, or moving the position. http://i.imgur.com/jqKXNpE.png

(Potion Hud) - http://i.imgur.com/USSyOas.png, maybe conflict with another mod? Cuz I deleted the config file, and all I did was lowwerd the hud to not cover the clock.

**Comment by OreCruncher** [comment]
Looks like the mod does some funky things with the rendering state so when Dynamic Surroundings does it's overly the settings are kinda messed up.  Looking at his source on GitHub it appears that they were fixed in the 1.8.x version.  I am going to work around this issue by increasing the priority of the Dynamic Surroundings rendering handler so it renders first.

**Comment by OreCruncher** [comment]
BETA build pushed to CurseForge: http://minecraft.curseforge.com/projects/dynamic-surroundings/files

**Comment by O13SC3N3** [comment]
Looks Good m8 :p http://imgur.com/kaGCwkt
