### ISSUE TITLE
Proper weather in modded dimensions, plus maybe the end

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#66]
Would it be possible to add weather to some common modded dimensions (Erebus, Aether, Twilight Forest), plus maybe something for the end?

Maybe end weather could consist of meteor showers (maybe possible damage to the player). There are probably other things that could be thought of, but, I don't have any ideas.

**Comment by OreCruncher** [comment]
Potentially.  Right now the weather I provide are effects and don't actually change the game mechanics.  Example, the Nether does not have precipitation in the Minecraft sense, but Dynamic Surroundings does have storms based on it's own mechanics and thus the dust, smoke, etc.

I could do the same things for other dimensions.  I have on my list to refactor the precipitation engine so that it is more modular and can provide more specific dimension effects as it relates to "storm intensity".

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
