### ISSUE TITLE
Apply presence footsteps to similar blocks

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#77]
Would it be possible to add an option to apply footstep sounds to similar blocks to those found in vanilla (i.e modded leaves)?

**Comment by OreCruncher** [comment]
Yes, it's possible.  It is on my list to do.  My plan is to do something similar to modded blocks sound support- have mod specific config files internal to the mod, and then allow an author to tweak using external files.  As simple as this sounds there is a bit of work I need to do in this area - have to convert the file format over to Json so it is "familiar" like the rest of the config files.

In general, though, if the block is not specifically configured it tries to use a "fallback" sound based on the material type.  For example, walking on Forestry wood planks still gives the same sound as walking on Vanilla wood planks because they are similar material types.  I believe the leaf walk sound will also apply to Forestry leaves - haven't checked that specifically.

EDIT: Just checked Forestry leaves and they have the "organic" block sound rather than leaves.  So this block type would be a candidate for a specific configuration.

**Comment by OreCruncher** [comment]
_BETA8_ will have support for (most) blocks from Forestry, BoP, and Growthcraft.

**Comment by OreCruncher** [comment]
Marking this as fixed for Foresty, BoP, and Growthcraft.  I am going to open another issue for the general "Footstep mod support" where other mods could be tracked.

**Comment by OreCruncher** [comment]
Latest BETA posted to CurseForge: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
