### ISSUE TITLE
Do not use feedback sounds as ambiance.

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#78]
At some point, you added the **minecraft:random.pop** sound (the one that plays when the player picks up an item) as a default block sound for Nether Wart. This is either a _very big mistake_ or a _very mean-spirited trick._ Sounds that trigger on gameplay events are an important feedback mechanism for the player, and they should _never ever_ play in any circumstance other than gameplay events.

It took me quite a while to figure out that I wasn't really picking up items, never mind what was actually causing the pickup sound to play. Imagine if it were an even more important sound that was playing when it shouldn't, like the hurt sound? You would cause players to first be extremely confused, then start to ignore that sound because it's playing when they're not taking damage, probably leading to death after not realizing that they're _actually taking damage_ this time. All due to a mod that claims to have no effect on gameplay. Psychological effects are still effects.

**Comment by OreCruncher** [comment]
Mean spirited? No.  Mistake? Maybe.  (I had a pack installed that altered the sounds and I forgot to remove it.)  In general your point about using a sound that players associate with specific effects is a good one.

To point out that the mod does not alter the _mechanics_ of game play.  It will affect the psychology of game play - sound and visuals do that - no way to avoid.  I have had requests from some other players about removing certain sounds because of these things.  It's why I am adding the capability to quickly cull/block sounds in an easy straight forward way.

(On my list is to do something about the nausea effect.  I am a person that can be affected adversely by visual effects and would like to change it.  There is a mod No Nausea that does this but I want to include this feature for my own reasons.)

**Comment by OreCruncher** [comment]
Latest BETA has the fix: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
