### ISSUE TITLE
Rain sound nullifies background noise?

### ISSUE THREAD

**Issue by Ariannae** [OreCruncher/BetterRain#83]
It began raining while in the Jungle and the background ambience completely stopped when the rain sound began to play. Presence Footsteps continued to play, and I couldn't tell if spot noises continued or not.

Is this intended, a bug, or can it just be changed via adding more sound channels?

**Comment by OreCruncher** [comment]
Yes, its intentional.  Some of the sounds, either biome or spot, will not play when it is raining, day, night, etc.  In this particular case the jungle background sound does not play when it is raining.

**Comment by Ariannae** [comment]
Good to know! Any chance of lowering the volume of sounds while it's raining instead of completely stopping them, or would this lead to performance issues?

**Comment by OreCruncher** [comment]
I will take this in two parts:
- Yes, it is possible to scale volume based on rain intensity.  It is an interesting idea.  Shouldn't be that much overhead.  However,
- It was intentional on my part to have the sound stop when raining.  Same effect can be heard in the Forest when raining - no birds and no crickets.  The reason has nothing to do with performance and more with "the birds, crickets, critters, etc. went home because it is raining".

With the recent changes I made to the number of sound channels my thought was to layer the background sounds.  Using the Forest as an example, the sound track could be separated out into two different tracks.  The first track would be the leaves rustling in the breeze type sound track.  The second track would be that of the animals (bird chirps, etc.).  Both of these could play at the same time.  As it relates to rain the first Forest sound track would continue to play (wind in the leaves), but the second track would stop because birds don't want to be out in rain.  This being said I need to get some decent tracks for doing this.  The same technique could apply to jungles as well.

**Comment by Ariannae** [comment]
I think that's what my concern was. Not so much, "Where'd all the wildlife go?", but more of, "It just got super quiet." So I'm in agreement with your proposed idea. I just didn't think that it should get dead silent when the rain started.
