### ISSUE TITLE
Background sounds play on Galacticraft planets

### ISSUE THREAD

**Issue by Haggle1996** [OreCruncher/BetterRain#88]
I was on the moon and noted the sound of tweeting birds. :)

**Comment by OreCruncher** [comment]
What biomes are on the moon?  Other planets as well?

**Comment by OreCruncher** [comment]
Here is a link for the biomes that are part of Galacticraft:  http://wiki.micdoodle8.com/wiki/Biomes.  Not sure how you get birds on the moon since the biome should be "moon".

This being said I know you can hear forest sounds when a world loads.  That is because things are ticking away on the client and the underlying code is saying that the player is in the Forest.  That should correct itself once the client is fully loaded and the correct biome is detected.

**Comment by Haggle1996** [comment]
Sorry for the delay; just got home from work.

It's permanent -- it always plays.

**Comment by OreCruncher** [comment]
What is the name of the biome you are standing in?  You can hit F3 to get the debug screen and it should tell you.

**Comment by Haggle1996** [comment]
'moon'. :)

**Comment by Haggle1996** [comment]
It seems it's picking up the sounds from where I was at last. When I arrive to the moon from the overworld, it carries the sounds that were appropriate in the last biome I was in. If I go to mars from the moon, everything is fine. If I go back to the moon from mars, it's fine. If I go to the overworld, then return to the moon, I'm back to birds.

**Comment by OreCruncher** [comment]
OK.  You are using the latest version of GalactiCraft?  Asking to make sure I pull the right binaries.

**Comment by Haggle1996** [comment]
I'm on version 3.0.12.437, which is not quite the latest, but newer than the recommended.

**Comment by OreCruncher** [comment]
Was hoping to figure out what is going on for this release cycle.  The Galacticraft Jenkins build server is down so I can't get the dev binaries.  Will work on this as soon as the dev binaries are available.

**Comment by OreCruncher** [comment]
I have it up and running, and travelled to the moon.  I am standing on the moon and I am not hearing any sounds.  Note that on the flight up and at the solar system map I could hear them - reason is because the player was still in overworld in a Forest biome despite the altitude or the solar system screen display.

About the only thing I can think of is adding some logic to cut off sound at altitude (world height).  This way when the player transitions to "space" there will be no sound.

EDIT:  I was using the equivalent of the current *.0.5.0BETA posted to CurseForge.

**Comment by OreCruncher** [comment]
The change going in is the addition of a new fake biome "OuterSpace".  When a player's Y value becomes >= the sky height (build height) of the dimension it will become this fake dimension.  There are no sounds attached to that biome so sounds associated with biome backgrounds should cease.  Of course, if I can find a decent space sound track I may add that. :)

BTW, may tweak the actual Y limit.  Some mods generate terrain right up to build height (ATG) and it may make more sense to have the threshold a bit higher than build height.

**Comment by OreCruncher** [comment]
Posted a BETA to CurseForge that should address this issue.

**Comment by Haggle1996** [comment]
Awesome, thank you!
