### ISSUE TITLE
[1.8.9] Crash with SpongeForge (Dynamic Surroundings)

### ISSUE THREAD

**Issue by ajthemacboy** [OreCruncher/BetterRain#89]
SpongeForge issue link: https://forums.spongepowered.org/t/spongeforge-crash-on-ftb-unstable-with-forge-1732/

Server log: https://gist.github.com/ajthemacboy/fa08dfdd69014249f5f3

SpongeForge: Latest version, Forge: 1732

**Comment by OreCruncher** [comment]
Looks like Sponge is wanting to do something with updateWeatherBody() as well which leads to a conflict.  Transform hook can be found [here](https://github.com/OreCruncher/BetterRain/blob/master/src/main/java/org/blockartistry/mod/DynSurround/asm/Transformer.java#L137).

Need feedback from the Sponge crew to figure out the best way to resolve without gutting a Dynamic Surroundings feature.

**Comment by OreCruncher** [comment]
Seems like two possible solutions:
- Rewrite to use mixins.  Not sure if mixins are supported on Forge w/o Sponge.
- Change the transformed to insert the hook and return at the top of the method without wiping it out.

Because of the nature of the change I will delay until the next release cycle (*.0.5.x).  Trying to get this cycle completed and to RELEASE.

EDIT: So I don't forget - https://forums.spongepowered.org/t/spongeforge-crash-on-ftb-unstable-with-forge-1732/11382/7

**Comment by OreCruncher** [comment]
Did a quick fix to get it working.  Will take on mixin conversion in a separate task.

**Comment by OreCruncher** [comment]
Release version pushed to CurseForge that should be compatible with SpongeForge
