### ISSUE TITLE
Feature Request: Global experience control via Server

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#9]
If it's not already the case, would it be possible for you to make it so that all players experience the same effects, as controlled by the server. For example, rather than one client seeing an Aurora in blue, and another seeing the same Aurora in Yellow, the server would control what they see, and ensure that they both see the same thing? The same principal would apply in the case of my Feature Request #7 .

**Comment by OreCruncher** [comment]
Where auroras are concerned there is a a preset for the aurora shape, and a color set that is used to color.  These two pieces of data are assigned to each aurora.  If two different players are looking at the same aurora they should have the same geometry and color set.  It is possible to have more than one aurora spawned in the world, and in that case each could have different geometries and colors.

**Comment by PitchBright** [comment]
Okay, so in theory… if I'm standing beside someone and we're both looking up at the same aurora, we should be seeing the same thing (shape and colour-wise)?

**Comment by OreCruncher** [comment]
Yep.  There may be variances in the undulation patterns because the aurora animation and timing is purely client side.  Specifically there are 4 presets for aurora geometry, and 9 color presets.  When an aurora spawns the server picks a geometry preset and color preset and sends that info to all applicable clients.  This information is also saved in the world data so if you were to stop/start Minecraft the aurora should come back with the same geometry and color.

**Comment by PitchBright** [comment]
Okay, that's perfect I think. Doesn't sound like there's anything I'm overlooking on that. Thanks so much!
