### ISSUE TITLE
Algal blooms

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#99]
This is one of those dumb ideas that come to to you at random, but, how feasible would adding stuff like red tides (water turning red in oceans due to certain microbes), algal blooms (some water turning a disgusting shade of green and becoming very murky) and bioluminescent algal blooms (actual thing and is rather cool, happens around coastal regions) be?

**Comment by OreCruncher** [comment]
1. Red Tides.  Interesting idea.  Not sure how I would implement something like that.  It would think it would hook into the biome water colorization code so it tints.
2. Algae blooms.  This would be like fog under water.  Most immediate thing I can think of is implementing as a game overlay.  It would be similar to how the pumpkin helmet works, just that in this case it would be a diffuse green tinted overlay that obscures vision.  Not sure exactly what the trigger conditions would be, and whether they would have to be synchronized across clients.
3. Bioluminescence.  This would be cool - kinda like algae that emits low level light like brown mushrooms.  This probably should be implemented as part of the algae code rather than something spliced in with Dynamic Surroundings.  Other possibility is to have a different texture for the algae that is a bit brighter to give the sense of luminescence without messing with lighting.

**Comment by Sunconure11** [comment]
IRL, Red Tides are often harmful to animals and people. How would harmful events be handled by this mod, if any?

**Comment by OreCruncher** [comment]
Yeah, familiar with red tide.  Lived in VA for a couple years near Virginia Beach.  Pretty nasty stuff.

If I do anything it would be strictly visual and not harm/effect mobs.  Trying to keep the mod to aesthetics.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
